apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configMap.name" . }}
data:
  k8s.yml: |
    {{ include "cellbase.labels" . | nindent 4 }}
  {{- if ( ne (len (.Files.Glob "conf/**.{xml,yml,yaml}")) 0) }}
  {{- (.Files.Glob "conf/**.{xml,yml,yaml}").AsConfig | nindent 2 }}
  {{- end }}
