{{- if .Values.worker.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pvcResources" . | quote }}
  labels:
    {{- include "cellbase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "pvResources" . | quote }}
  storageClassName: {{ include "pvcStorageClassName" . }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pvcWorkdir" . | quote }}
  labels:
    {{- include "cellbase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default
  volumeMode: Filesystem
{{- end -}}
