{{- if and .Values.worker.enabled .Values.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.name }}
  labels:
    {{- include "cellbase.labels" . | nindent 4 }}
{{- end -}}
