{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app: {{  .Values.worker.name  }}
    {{- include "cellbase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{  .Values.worker.name  }}
      {{- include "cellbase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name  }}
        {{- include "cellbase.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.worker.name }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: {{ tpl .Values.worker.image.repository . | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["sleep", "31536000"]
          env:
            - name: "CELLBASE_DATABASES_MONGODB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "cellbase.secretName" . }}
                  key: password
          envFrom:
            - configMapRef:
                name: {{ include "configMapEnv.name" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
          - name : conf
            mountPath: /opt/cellbase/conf
          - name : resources
            mountPath: /data/resources/
          - name : home
            mountPath: /home/cellbase/
      volumes:
      - name: conf
        configMap:
          name: {{ include "configMap.name" . }}
      - name: resources
        persistentVolumeClaim:
          claimName: {{ include "pvcResources" . | quote}}
      - name: home
        persistentVolumeClaim:
          claimName: {{ include "pvcWorkdir" . | quote}}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
