# https://cert-manager.io/docs/installation/supported-releases/


installCRDs: true

nodeSelector:
  kubernetes.io/os: linux

webhook:
  nodeSelector:
    kubernetes.io/os: linux

cainjector:
  nodeSelector: 
    kubernetes.io/os: linux