version: '2'

services:
  app:
    build: cellbase-rest
    ports:
    - 9090
    depends_on:
    - mongodb
    hostname: cellbase-rest-zetta
    container_name: cellbase-rest-zetta

  mongodb:
    image: mongo
    ports:
    - 27017:27017
    hostname: mongodb
    container_name: mongodb
    


