name: Java Unit tests

on: [push, pull_request]

matrix:
  mongodb-version: ["4.0", "4.2"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Launch MongoDB 
      run: ./mongo-installation.sh
    - name: Build with Maven
      run: mvn -T 2 clean install
