name: CellBase Main

on:
  push:
    branches:
      - develop
      - next

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mongodb-version: ["4.0", "4.2"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone and build java-common-libs
      run: cd ~ && git clone -b develop https://github.com/opencb/java-common-libs.git && cd ~/java-common-libs && mvn -T 2 clean install -DskipTests && cd $GITHUB_WORKSPACE
    - name: Clone and build biodata
      run: cd ~ && git clone -b develop https://github.com/opencb/biodata.git && cd ~/biodata && mvn -T 2 clean install -DskipTests && cd $GITHUB_WORKSPACE
    - name: Launch MongoDB 
      run: sudo docker run --name mongo -d -p 27017:27017 mongo:${{ matrix.mongodb-version }}
    - name: Build with Maven
      run: mvn install
    - name: Generate Javadocs
      run: mvn javadoc:aggregate
    - name: Deploy Javadocs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: next # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/site # The folder the action should deploy.
    - name: Export IOTCL for GPG
      run: echo ::set-env name=GPG_TTY::$(tty)
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1.1.0
      with:
        gpg_private_key: ${{ secrets.MAVEN_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.MAVEN_PASSPHRASE }}
        nexus_username: ${{ secrets.MAVEN_NEXUS_USER }}
        nexus_password: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
