name: PyCellBase main workflow

on:
  push:
    branches:
      - next

jobs:
  validate:
    name: Run PyLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Python Pylin GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc cellbase-client/src/main/python
