name: testing javadoc copying (to be deleted)

on:
  push:
    branches:
      - develop
      - next
    paths:
      - '**.java'
      - '**.xml'
      - '**.yml'

jobs:
  deploy:
    name: Copy over javadocs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh                        # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_NEXUS_USER       # env variable for username in deploy
          server-password: MAVEN_NEXUS_PASSWORD   # env variable for token in deploy

      ## Generate and deploy Javadocs
      - name: Get CellBase version
        id: get_version
        run: echo ::set-output name=VERSION::$(grep '<cellbase.version>' pom.xml | sed 's/cellbase.version//g' | sed 's/[<>/ ]//g')
      - name: Generate Javadocs
        run: mvn javadoc:aggregate

      - name: Create a ssh key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SCP_PUBLIC_KEY }}" >> ~/.ssh/key
      - name: Copy javadocs to OpenCB server
        run: rsync -av --delete target/site/apidocs/* ${{ secrets.SCP_SITE_USER }}@128.232.224.128:/mnt/data/opencb/cellbase/javadocs/${{ steps.get_version.outputs.VERSION }}


