name: CellBase Develop workflow (TEMP)

on:
  push:
    branches:
      - develop
      - next
    paths:
      - '**.java'
      - '**.xml'
      - '**.yml'

jobs:
  site:
    name: Generate Maven site
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Site with Maven CLI
        run: mvn site
      - name: Prepare Maven Site submodules
        run: cp -r cellbase-app/target/site target/site/cellbase-app &&
          cp -r cellbase-client/target/site target/site/cellbase-client &&
          cp -r cellbase-core/target/site target/site/cellbase-core &&
          cp -r cellbase-lib/target/site target/site/cellbase-lib &&
          cp -r cellbase-server/target/site target/site/cellbase-server
      - name: Get CellBase version
        id: get_version
        run: echo ::set-output name=VERSION::$(grep '<cellbase.version>' pom.xml | sed 's/cellbase.version//g' | sed 's/[<>/ ]//g')
      - name: Get current date in YYMMDD format
        id: get_date
        run: echo ::set-output name=YYMMDD::$(date +%Y%m%d)
      - name: Get current date in HHMMSS format
        id: get_time
        run: echo ::set-output name=HHMMSS::$(date +%H%M%S)
      #      - name: Deploy mvn site to server
      #        id: deploy_site
      #        uses: Pendect/action-rsyncer@v1.1.0
      #        env:
      #          DEPLOY_KEY: ${{secrets.SCP_PRIVATE_KEY}}
      #        with:
      #          flags: '-avzr'
      #          options: ''
      #          ssh_options: 'mkdir --parents /mnt/data/opencb/cellbase/site/${{ steps.get_version.outputs.VERSION }}/${{ steps.get_date.outputs.YYMMDD}}/${{ steps.get_time.outputs.HHMMSS }}-${{ github.sha }}/'
      #          src: 'target/site'
      #          dest: '${{ secrets.SCP_SITE_USER }}@128.232.224.128:/mnt/data/opencb/cellbase/site/${{ steps.get_version.outputs.VERSION }}/${{ steps.get_date.outputs.YYMMDD }}/${{ steps.get_time.outputs.HHMMSS }}-${{ github.sha }}'
      - name: Deploy with rsync
        uses: BuildPC/rsync-with-ssh-github-actions@master
        with:
          key: ${{ secrets.SCP_PRIVATE_KEY }}
          host: 128.232.224.128
          port: 22
          user: ${{ secrets.SCP_SITE_USER }}
          destination: /mnt/data/opencb/cellbase/site/${{ steps.get_version.outputs.VERSION }}/${{ steps.get_date.outputs.YYMMDD }}/${{steps.get_time.outputs.HHMMSS }}-${{ github.sha }}
          # runs this on remote server
          ssh_before: |
            mkdir --parents /mnt/data/opencb/cellbase/site/${{ steps.get_version.outputs.VERSION }}/${{ steps.get_date.outputs.YYMMDD}}/${{steps.get_time.outputs.HHMMSS }}-${{ github.sha }}
