name: CellBase github workflow - to be deleted

on:
  push:
    branches:
      - next

jobs:
  deploy:
    name: Build and deploy CellBase libs, Java docs and Docker images in Maven Central and DockerHub repositories
    runs-on: ubuntu-18.04
    steps:
      ## Deploy in GitHub repository
      - name: Deploy to GitHub packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ~/.m2
          echo "<settings><servers><server><id>github</id><username>opencb</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy -P deploy-github
