name: testing javadoc copying (to be deleted)

on:
  push:
    branches:
      - develop
      - next
    paths:
      - '**.java'
      - '**.xml'
      - '**.yml'

jobs:
  deploy:
    name: Copy over javadocs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh                        # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_NEXUS_USER       # env variable for username in deploy
          server-password: MAVEN_NEXUS_PASSWORD   # env variable for token in deploy

      ## Generate and deploy Javadocs
      - name: Get CellBase version
        id: get_version
        run: echo ::set-output name=VERSION::$(grep '<cellbase.version>' pom.xml | sed 's/cellbase.version//g' | sed 's/[<>/ ]//g')
      - name: Generate Javadocs
        run: mvn javadoc:aggregate

#      - name: Create a ssh key
#        run: |
#          mkdir ~/.ssh
#          echo "${{ secrets.SCP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          echo "${{ secrets.SCP_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
#      - name: Copy javadocs to OpenCB server
#        env:
#          RSYNC_PASSWORD: ${{ secrets.SCP_SITE_PASSWORD }}
#        run: sshpass -p "${{ secrets.SCP_SITE_PASSWORD }}" rsync -av --delete  target/site/apidocs/org/opencb/cellbase/app/cli/admin/executors/class-use/* ${{ secrets.SCP_SITE_USER }}@128.232.224.128:/mnt/data/opencb/cellbase/javadocs/${{ steps.get_version.outputs.VERSION }}
#        run: rsync -av --delete target/site/apidocs/* ${{ secrets.SCP_SITE_USER }}@128.232.224.128:/mnt/data/opencb/cellbase/javadocs/${{ steps.get_version.outputs.VERSION }}
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.SCP_PRIVATE_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'target/site/apidocs/*'
          dest: '${{ secrets.SCP_SITE_USER }}@128.232.224.128:/mnt/data/opencb/cellbase/javadocs/${{ steps.get_version.outputs.VERSION }}'
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"