name: CellBase github packages test (to be deleted)

on:
  push:
    branches:
      - next

jobs:
  deploy:
    name: Deploy to github package registry
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to GitHub packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ~/.m2
          echo "<settings><servers><server><id>github</id><username>opencb</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy -P deploy-github
